// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmlxqiWtQ6u1EGw-hhXlLOfcNvokaVCM',
    appId: '1:953363945085:web:5770183d6fba5e754d0314',
    messagingSenderId: '953363945085',
    projectId: 'exam-test-629bd',
    authDomain: 'exam-test-629bd.firebaseapp.com',
    storageBucket: 'exam-test-629bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKq4eVTWAsmvtzmxPbQbeb5HZnZsrriQ',
    appId: '1:953363945085:android:74c5dcf4e1819c084d0314',
    messagingSenderId: '953363945085',
    projectId: 'exam-test-629bd',
    storageBucket: 'exam-test-629bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLFwjzDutAnFr-tgX9Ihb4W40IrScXfg',
    appId: '1:953363945085:ios:84c319e1be690dc04d0314',
    messagingSenderId: '953363945085',
    projectId: 'exam-test-629bd',
    storageBucket: 'exam-test-629bd.appspot.com',
    iosBundleId: 'com.example.examTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLFwjzDutAnFr-tgX9Ihb4W40IrScXfg',
    appId: '1:953363945085:ios:aabc97401747a20d4d0314',
    messagingSenderId: '953363945085',
    projectId: 'exam-test-629bd',
    storageBucket: 'exam-test-629bd.appspot.com',
    iosBundleId: 'com.example.examTest.RunnerTests',
  );
}
